[package]
name = "cloudcore-lib"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "cloudcore",
    "ffi",
    "ios",
    "android",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true